# Generated by Django 3.0.5 on 2020-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_comment_genre_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars'), (6, 'Six Stars'), (7, 'Seven Stars'), (8, 'Eight Stars'), (9, 'Nine Stars'), (10, 'Ten Stars')]),
        ),
    ]
